### ISSUE TITLE
Filters break digipeater behavior

### ISSUE THREAD

**Issue by PhirePhly** [PhirePhly/aprx#11]
Adding filters to a digipeater source block breaks standard WIDEn-N digipeating on that digipeater.

    <digipeater>
        transmitter     $mycall
        <source>
            source            $mycall
            filter "-b/CALL*"
        </source>
    </digipeater>

Bug reported by Beau <bvdgroenendaal@gmail.com>
https://groups.google.com/forum/#!topic/aprx-software/qwh3UAJ3mAM

**Comment by oh2mqk** [comment]
Probably another logic error -- if a filter is defined at all, it says what to do.  If no filter is defined, then digipeat default rules are applied.

It really should be "apply filters, non-matching result is to pass on to default rules".
But for "-" prefix the non-match path is apparently "reject all".  Oops.

**Comment by w8vfr** [comment]
Just curious if this bug is 'targeted' for a fox anytime soon. I have several digIgates on the air, and I do indeed wish to use the filtering feature in the digi section. If I can be of any help in testing a new version, please contact me. 

Thanks
Curtis
W8VFR

**Comment by PhirePhly** [comment]
I was hoping to start poking at it after this weekend; currently running
communications support for a triathlon this weekend. I'd expect to have a
patch up within 7 days, life permitting.

**Comment by w8vfr** [comment]
Fantastic! I am about to re-arrange several digi/igate stations and move into aprx via Raspberry-PI. The "broken" but handy filter feature is ideal for the very busy Cincinnati / Dayton, OH area I am in. Hamvention is comming soon! 

Thank You for your efforts!

**Comment by samwathegreat** [comment]
Just wanted to say thanks to PhirePhly for taking this filter bug on.  Looking forward to being able to use the filter feature without losing normal digi operation.

You Rock!

Sean
KS9N

**Comment by w8vfr** [comment]
I now have the 2nd Raspberry Pi2 based aprx unit up and running. Awaiting the patch.

Thanks to all,

73s

W8VFR

**Comment by samwathegreat** [comment]
Any updates?

**Comment by PhirePhly** [comment]
What happens if you use a source block such as:

     <source>
         source         $mycall
         filter         -b/W6KWF-5        # always block these
         filter t/*
     </source>

Page 40 of the aprx manual, item 8.1, states that you need to match at least one filter to be digipeated if you use any filters, which seems to be a pretty major assumption in how the filtering is architected. This example would then allow ALL types of packets, except those from W6KWF-5.

I've performed only minimal testing, since I can't currently find any of my VHF antennas.

**Comment by samwathegreat** [comment]
Thanks for looking into this!!!  So perhaps there was no bug at all and our syntax was just incorrect.

When I have a chance, I will test and report back.


KS9N

**Comment by w8vfr** [comment]
Initial testing shows good results. I will update after it 'soaks' a while. Thank you for looking into this issue.

**Comment by PhirePhly** [comment]
> So perhaps there was no bug at all and our syntax was just incorrect.

I would certainly say there is a bug here, but it's with the defined behavior and/or the documentation and not the implementation. Blacklisting individual problematic stations is likely needed often enough that it should be called out as an explicit example in the manual, and shouldn't stump all of us for two months.

**Comment by w8vfr** [comment]
Excellent idea, putting an example into the manual. Please advise if i can
assist in any way. So far the station has performed 100% since the "filter
t/*" addition in the digi section.

73s,
Curtis
W8VFR

On Sat, Aug 8, 2015 at 11:47 PM, Kenneth Finnegan <notifications@github.com>
wrote:

> So perhaps there was no bug at all and our syntax was just incorrect.
>
> I would certainly say there is a bug here, but it's with the defined
> behavior and/or the documentation and not the implementation. Blacklisting
> individual problematic stations is likely needed often enough that it
> should be called out as an explicit example in the manual, and shouldn't
> stump all of us for two months.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PhirePhly/aprx/issues/11#issuecomment-129101761>.
>



-- 
*So we fix our eyes not on what is seen, but on what is unseen, since what
is seen is temporary, but what is unseen is eternal.  *2 Corinthians 4:18

Why use 'Windows', since there is a door? -> Linux!

**Comment by w8vfr** [comment]
I'd like to comment on this again after several stations have 'soaked' a while running with the suggested filter filter t/* appended to the -b/CALL list. 

So far, no issues. I would consider this issue resolved, but again would ask for an addition to the manual to detail the 'correct' filter procedure. (Now if we can just figure a way to stop the excess PATH variable abuse most aprs running hams seem to like.... we would be good! )

**Comment by w8vfr** [comment]
Last comment was 12 days ago. Five sites running this configuration, no issues. Also added radius and area filter to the mix, again no issues. 

Solved issues it would seem.
