### ISSUE TITLE
Missing version string in build system breaks APRS-IS login

### ISSUE THREAD

**Issue by PhirePhly** [PhirePhly/aprx#15]
APRS-IS login depends on there being two software ident tokens before any "filter ..." options. When APRX is built incorrectly with a "" version string, the APRS-IS server interprets "filter" as the version and can not correctly parse the login string.

Proposed solution is to somewhere between the build system and the APRS-IS login function substitute "" with "UNKNOWN"

**Comment by patrickdk77** [comment]
Problem is cause of the VERSION change to use git, if build was done outside of a git repo, the git command fails, and gives a blank VERSION, in Makefile.in

# generate version strings
VERSION = $(shell git describe --tags | cut -b 2-)
#VERSION = @VERSION_STRING@

**Comment by PhirePhly** [comment]
Fixed with help from Patrick Domack <patrickdk@patrickdk.com> in commit d090640b1a142ac10e22ffdc4e1022cac2300b31
