### ISSUE TITLE
Please update README to show this repo

### ISSUE THREAD

**Issue by n2ygk** [PhirePhly/aprx#30]
I believe this is the actively maintained APRX repo. However, when I looked in the README, it references an apparently dead [SVN repo](http://repo.ham.fi/svn/aprx). Please update the docs to make it clear that this is the place, if it in fact is. Thanks.

**Comment by PhirePhly** [comment]
Confirmed. You are correct and I've clearly blown it missing those links for the last two years. I'll try and fix this when I get home tonight.

**Comment by PhirePhly** [comment]
Thanks again for opening this ticket. It's easy as the developer to forget to check the new user experience, so your feedback is appreciated.
