### ISSUE TITLE
Support for preamble and tx tail?

### ISSUE THREAD

**Issue by mumrah** [PhirePhly/aprx#44]
Is it possible to configure the KISS preamble and tx tail? The packets from my TNC are pretty short so I'm not getting decoded often. If I fire up Xastir and use the same TNC with a longer preamble and tail, I get decoded more reliably.

**Comment by PhirePhly** [comment]
It is supported via the initstring value, which is discussed in this other issue: https://github.com/PhirePhly/aprx/issues/21

What TNC do you have where you're not able to set the preamble once and have it retain the setting indefinitely? Do also appreciate that TNCs with KISS support beyond data frames is becoming increasingly rare.

The tx tail value should not make any difference, and it should always be set to the shortest value allowed.
