### ISSUE TITLE
Feature Request: Compressed position format support

### ISSUE THREAD

**Issue by jesshaas** [PhirePhly/aprx#52]
Unless I am missing something it looks like aprx doesn't currently support compressed position in beacons. They can be achieved using the raw beacon feature but it would be nice if they were supported natively. Also having the ability for the digipeater to convert incoming packets to compressed format before digipeating would be nice.

**Comment by kd7lxl** [comment]
On the latter of your two requests, manipulating a packet would defeat dupe protection, so it's a very bad thing. Digipeater, igate, and APRS server software must never modify the packet source, destination, or payload.

**Comment by jesshaas** [comment]
Makes sense. I only thought of it because it was mentioned in the aprs spec as some digipeaters doing it on aprs.org.

**Comment by PhirePhly** [comment]
1. Aprx is meant to be used as APRS infrastructure, so the expected beacon interval is 10-30 minutes, so the relative advantage of compressed location packets is small compared to 30 second-3 minute tracker intervals where it makes a difference. This is why I decided to not support compressed packets for the sake of simplicity and keeping the packets human readable. If someone would like to shave 30-40ms off their 10 minute beacon interval, I'd argue their need is niche enough to warrant using the raw packet option.
2. Modifying the UI contents of other station's packets fundamentally breaks the underlying assumption used for APRS de-duplication behavior. I wish Bob would stop posting these sorts of thoughts on what could ideally happen like they're supposed to be implemented. This would be a huge misfeature.

Thanks for the thoughts.

**Comment by kd7lxl** [comment]
IMO, the primary benefit of compressed beacons is the increased precision (again, not really critical for an igate), not the length.

**Comment by jesshaas** [comment]
What about objects? Add several objects and e are talking higher transmit time. More than just actual channel usage I am thinking of decreased chance of collision.

I am all for simplicity but considering everyone uses software to interpert their packets it seems smaller encoding should trump human readability. Especially when the encoding is already implemented.

**Comment by kd7lxl** [comment]
It's not like there's anything preventing you from using compressed positions for objects now. It works great with the raw feature.
