### ISSUE TITLE
APRXxx tocall is parsed as APRSmax

### ISSUE THREAD

**Issue by MoTLD** [PhirePhly/aprx#61]
First, thanks for all your hard work on APRX, it's awesome!

Now, the issue: apparently the old APRSmax used APRXxx for its tocall, and at least one system, the CWOP Weather Quality Reporter, reports my APRX station as running APRSmax (https://weather.gladstonefamily.net/site/AV633) as well as other stations with APRXxx tocalls. Is APRSmax likely still in use anywhere? Should I just send the CWOP folks an email letting them know what I'm running and suggesting they change their system? My cursory googling didn't find much on APRSmax, so I assume it's defunct, but if not, I'm afraid there may be a conflict.

73

-Rob, KG4WGN

**Comment by PhirePhly** [comment]
APRXmax and APRX have separate TNCIDs  allocated to them. It's unlikely that anyone is still using APRXmax, but even if they were, anyone parsing APRX TNCIDs as APRSmax aren't correctly interpreting the database

**Comment by MoTLD** [comment]
I see now, in tocalls.txt APRSmax is APRXxx with xx>40, APRX ("OH2MQK's igate") is xx<39. I'll contact the CWOP site and let them know they've got a misconfiguration or an out of date tocalls list. Thanks!

**Comment by W0CHP** [comment]
> I see now, in tocalls.txt APRSmax is APRXxx with xx>40, APRX ("OH2MQK's igate") is xx<39. I'll contact the CWOP site and let them know they've got a misconfiguration or an out of date tocalls list. Thanks!

Good luck. Phillip Gladstone, the maintainer of the CWOP site, etc. has been MIA for over a year. We are all waiting on bug fixes on his (closed) site and backend.
