### ISSUE TITLE
make: "/root/aprx/Makefile" line 54: Missing dependency operator

### ISSUE THREAD

**Issue by KenwoodFox** [PhirePhly/aprx#63]
Hey all! Trying to build aprx and getting this error.

```~/aprx on master > make clean                                                with root@aprs at 04:48:20
make: "/root/aprx/Makefile" line 54: Missing dependency operator
make: Unknown modifier '%'
make: Unknown modifier '%'
make: "/root/aprx/Makefile" line 57: Need an operator
make: Unknown modifier '%'
make: Unknown modifier '%'
make: "/root/aprx/Makefile" line 60: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /root/aprx```

I'm on FreeBSD 12.1-RELEASE

thanks for reading!

**Comment by videobuff** [comment]
show us the problem when compiling with make V=s

**Comment by KenwoodFox** [comment]
Like this?

```make V=s
make: "/root/aprx/Makefile" line 54: Missing dependency operator
make: Unknown modifier '%'
make: Unknown modifier '%'
make: "/root/aprx/Makefile" line 57: Need an operator
make: Unknown modifier '%'
make: Unknown modifier '%'
make: "/root/aprx/Makefile" line 60: Need an operator
make: Fatal errors encountered -- cannot continue
make: stopped in /root/aprx```

**Comment by videobuff** [comment]
I'm running it on my Ubuntu machine and it shows no error. I don't have free BSD. This is my line 54: prepare: $(target/stamp-compile)
No % to be seen, nut I am not an expert.

Can you compile Openwrt without aprx  and without problems ?

**Comment by videobuff** [comment]
Just to be sure..... THis is my Makefile
`# Makefile for OpenWrt
#
# Copyright (C) 2007 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

TOPDIR:=${CURDIR}
LC_ALL:=C
LANG:=C
TZ:=UTC
export TOPDIR LC_ALL LANG TZ

empty:=
space:= $(empty) $(empty)
$(if $(findstring $(space),$(TOPDIR)),$(error ERROR: The path to the OpenWrt directory must not include any spaces))

world:

export PATH:=$(TOPDIR)/staging_dir/host/bin:$(PATH)

ifneq ($(OPENWRT_BUILD),1)
  _SINGLE=export MAKEFLAGS=$(space);

  override OPENWRT_BUILD=1
  export OPENWRT_BUILD
  GREP_OPTIONS=
  export GREP_OPTIONS
  CDPATH=
  export CDPATH
  include $(TOPDIR)/include/debug.mk
  include $(TOPDIR)/include/depends.mk
  include $(TOPDIR)/include/toplevel.mk
else
  include rules.mk
  include $(INCLUDE_DIR)/depends.mk
  include $(INCLUDE_DIR)/subdir.mk
  include target/Makefile
  include package/Makefile
  include tools/Makefile
  include toolchain/Makefile

$(toolchain/stamp-compile): $(tools/stamp-compile)
$(target/stamp-compile): $(toolchain/stamp-compile) $(tools/stamp-compile) $(BUILD_DIR)/.prepared
$(package/stamp-compile): $(target/stamp-compile) $(package/stamp-cleanup)
$(package/stamp-install): $(package/stamp-compile)
$(target/stamp-install): $(package/stamp-compile) $(package/stamp-install)
check: $(tools/stamp-check) $(toolchain/stamp-check) $(package/stamp-check)

printdb:
	@true

prepare: $(target/stamp-compile)

clean: FORCE
	rm -rf $(BUILD_DIR) $(STAGING_DIR) $(BIN_DIR) $(OUTPUT_DIR)/packages/$(ARCH_PACKAGES) $(BUILD_LOG_DIR) $(TOPDIR)/staging_dir/packages

dirclean: clean
	rm -rf $(STAGING_DIR_HOST) $(STAGING_DIR_HOSTPKG) $(TOOLCHAIN_DIR) $(BUILD_DIR_BASE)/host $(BUILD_DIR_BASE)/hostpkg $(BUILD_DIR_TOOLCHAIN)
	rm -rf $(TMP_DIR)

ifndef DUMP_TARGET_DB
$(BUILD_DIR)/.prepared: Makefile
	@mkdir -p $$(dirname $@)
	@touch $@

tmp/.prereq_packages: .config
	unset ERROR; \
	for package in $(sort $(prereq-y) $(prereq-m)); do \
		$(_SINGLE)$(NO_TRACE_MAKE) -s -r -C package/$$package prereq || ERROR=1; \
	done; \
	if [ -n "$$ERROR" ]; then \
		echo "Package prerequisite check failed."; \
		false; \
	fi
	touch $@
endif

# check prerequisites before starting to build
prereq: $(target/stamp-prereq) tmp/.prereq_packages
	@if [ ! -f "$(INCLUDE_DIR)/site/$(ARCH)" ]; then \
		echo 'ERROR: Missing site config for architecture "$(ARCH)" !'; \
		echo '       The missing file will cause configure scripts to fail during compilation.'; \
		echo '       Please provide a "$(INCLUDE_DIR)/site/$(ARCH)" file and restart the build.'; \
		exit 1; \
	fi

checksum: FORCE
	$(call sha256sums,$(BIN_DIR),$(CONFIG_BUILDBOT))

diffconfig: FORCE
	mkdir -p $(BIN_DIR)
	$(SCRIPT_DIR)/diffconfig.sh > $(BIN_DIR)/config.seed

prepare: .config $(tools/stamp-compile) $(toolchain/stamp-compile)
	$(_SINGLE)$(SUBMAKE) -r diffconfig

world: prepare $(target/stamp-compile) $(package/stamp-compile) $(package/stamp-install) $(target/stamp-install) FORCE
	$(_SINGLE)$(SUBMAKE) -r package/index
	$(_SINGLE)$(SUBMAKE) -r checksum

.PHONY: clean dirclean prereq prepare world package/symlinks package/symlinks-install package/symlinks-clean

endif
`

**Comment by KenwoodFox** [comment]
@videobuff Heres mine,  Im not a huge expert either. The build process should be the same for unix as well as linux?

**Comment by KenwoodFox** [comment]
Not sure how id compile openwrt on its own.

**Comment by kevans91** [comment]
I suspect you're using make when you should be using gmake instead (devel/gmake)

**Comment by KenwoodFox** [comment]
I think you're right, im actually installing gmake right now, I noticed on the top of the makefile it said it used gnu bits and bops, lets see if gmake works.

**Comment by KenwoodFox** [comment]
Yep, that was the issue. Installed gmake `pkg install gmake` and used `gmake` in place of `make` and it worked fine.
